[build-system]
requires = ["setuptools", "setuptools_scm"]
build-backend = "setuptools.build_meta"

[project]
name = "bogus_py"
description = "A Python package for data processing at the OGU, Bristol"
version = "0.0.1"
dependencies = [
    "pandas>=2.0.0",
    "xlrd>=2.0.0"
]
requires-python = ">=3.11"
authors = [
    {name = "Nick Hall", email = "nick.b.hall@bristol.ac.uk"}
]
readme = "README.md"

[project.urls]
Homepage = "https://github.com/ogubristol/bogus_py"

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.package.find]
where = ["src"]
